trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: iis-ci
    trigger:
      branches:
        include:
          - master


variables:
  - group: git-variable-group

stages:
- stage: Deploy
  jobs:
  - deployment: DeployWebsite
    displayName: Deploy Website
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none
          
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: 'sampleapp_v1'

          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'sampleapp_v1'
              Package: '$(Pipeline.Workspace)/CI/myArtifact/iis-app.zip'
              TakeAppOfflineFlag: true

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'sampleapp_v1'
