trigger: none

# resources:
#   pipelines:
#   - pipeline: CI
#     source: iis-ci
#     trigger:
#       branches:
#         include:
#           - master

variables:
  - group: git-variable-group  # Reference to the variable group

stages:
- stage: DeployToStaging
  displayName: "Deploy to Staging (Green Environment)"
  jobs:
  - deployment: DeployWebsiteGreen
    displayName: Deploy Website Green
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none
          
          # - task: IISWebAppManagementOnMachineGroup@0
          #   inputs:
          #     IISDeploymentType: 'IISWebsite'
          #     ActionIISWebsite: 'StopWebsite'
          #     StartStopWebsiteName: 'sampleapp_v2'

          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'sampleapp_v2'
              Package: '$(Pipeline.Workspace)/CI/myArtifact/iis-app.zip'

- stage: SwapBindings
  displayName: 'Swap Staging to Production'
  dependsOn: DeployToStaging
  jobs:
  - deployment: SwapBlueGreen
    displayName: 'Swap IIS Bindings for Blue-Green Deployment'
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Swap IIS Bindings'
            inputs:
              targetType: 'inline'
              script: |
                Import-Module WebAdministration

                # Define site names and bindings
                $prodSite = "sampleapp_v1"
                $stagingSite = "sampleapp_v2"
                $prodHost = "gunna.sreecharan.in"
                $stagingIP = "*" # Replace with the specific IP if the staging site uses a particular IP (e.g., "192.168.1.10")

                # Remove production binding from the current production site
                Remove-WebBinding -Name $prodSite -BindingInformation "*:80:$prodHost" -Protocol http

                # Remove IP-based binding from the staging site
                Remove-WebBinding -Name $stagingSite -BindingInformation "$stagingIP:80:" -Protocol http

                # Add production binding to the new site
                New-IISSiteBinding -Name $stagingSite -BindingInformation "*:80:$prodHost" -Protocol http

                # Add IP-based binding back to the old production site
                New-IISSiteBinding -Name $prodSite -BindingInformation "$stagingIP:80:" -Protocol http

                Write-Host "Binding swap complete: $prodHost -> $stagingSite and $stagingIP -> $prodSite"

- stage: Rollback
  displayName: "Rollback"
  dependsOn: SwapBindings
  condition: failed()
  jobs:
  - deployment: RollbackBindings
    displayName: "Rollback IIS Bindings"
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Rollback IIS Bindings'
            inputs:
              targetType: 'inline'
              script: |
                Import-Module WebAdministration

                # Define site names and bindings
                $prodSite = "sampleapp_v1"
                $stagingSite = "sampleapp_v2"
                $prodHost = "gunna.sreecharan.in"
                $stagingIP = "*"  # Replace with the specific IP if the staging site uses a particular IP (e.g., "192.168.1.10")

                # Track the previous binding information
                $prodHostBinding = "*:80:$prodHost"
                $stagingIPBinding = "$stagingIP:80:"

                # Rollback the bindings to previous state
                Write-Host "Rolling back IIS bindings to previous state"
                
                # Remove current bindings
                Remove-WebBinding -Name $prodSite -BindingInformation "*:80:$prodHost" -Protocol http
                Remove-WebBinding -Name $stagingSite -BindingInformation "$stagingIP:80:" -Protocol http

                # Add original bindings back
                New-IISSiteBinding -Name $stagingSite -BindingInformation "*:80:$prodHost" -Protocol http
                New-IISSiteBinding -Name $prodSite -BindingInformation "$stagingIP:80:" -Protocol http

                Write-Host "Rollback complete"