trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: iis-ci
    trigger: none

variables:
  - group: git-variable-group  # Reference to the variable group

stages:
- stage: Deploy
  jobs:
  - deployment: DeployWebsite
    displayName: Deploy Website
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none
          
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: 'sampleapp'
              
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'sampleapp'
              Package: '$(Pipeline.Workspace)/CI/$(ARTIFACT_NAME)-$(GIT_TAG)/iis-app.zip'

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'sampleapp'
