trigger: none

pool:
  name: "linuxpool"

stages:

- stage: Build
  displayName: Build
  jobs:

  - job: Restore
    displayName: Restore
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: "**/*.csproj"

  - job: Build
    displayName: Build
    dependsOn: Restore
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: "build"
        projects: "**/*.csproj"
        arguments: "--configuration Release"

- stage: Publish
  displayName: Publish
  jobs:

  - job: Publish
    displayName: Publish
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: "publish"
        projects: "**/*.csproj"
        arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"

  - job: PublishBuildArtifact
    displayName: Publish Build Artifact
    dependsOn: Publish
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "iis-app-v1.0"