trigger: 
  branches:
    include:
      - master

pool:
  name: "linuxpool"

stages:

- stage: Build
  displayName: Build
  jobs:

  - job: Restore
    displayName: Restore
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: "**/*.csproj"

  - job: Build
    displayName: Build
    dependsOn: Restore
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: "build"
        projects: "**/*.csproj"
        arguments: "--configuration Release"

- stage: Publish
  displayName: Publish
  jobs:

  - job: Publish
    displayName: Publish
    steps:

    - script: |
        echo "Fetching the latest Git tag..."
        git fetch --tags
        export TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "##vso[task.setvariable variable=GIT_TAG]$TAG"
        echo "Git tag is: $TAG"
      displayName: "Retrieve Git Tag"

    - task: DotNetCoreCLI@2
      inputs:
        command: "publish"
        projects: "**/*.csproj"
        arguments: "--configuration Release --output $(Build.ArtifactStagingDirectory)"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: "$(Build.ArtifactStagingDirectory)"
        ArtifactName: "app-$(GIT_TAG)"