trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: iis-ci
    trigger:
      branches:
        include:
          - master

variables:
  - group: git-variable-group  # Reference to the variable group

stages:
- stage: Deploy
  jobs:
  - deployment: DeployWebsite
    displayName: Deploy Website
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: '$(ARTIFACT_NAME)-$(GIT_TAG)'
              downloadPath: '$(System.ArtifactsDirectory)'
                    
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'sampleapp'
              Package: '$(Pipeline.Workspace)/CI/$(ARTIFACT_NAME)-$(GIT_TAG)/iis-app.zip'