trigger: none

resources:
  pipelines:
  - pipeline: CI
    source: iis-ci
    trigger:
      branches:
        include:
          - master

variables:
  - group: git-variable-group  # Reference to the variable group

stages:
- stage: Deploy
  jobs:
  - deployment: DeployWebsite
    displayName: Deploy Website
    environment: dev.dev-vm
    strategy:
      runOnce:
        deploy:
          steps:

          - checkout: none

          - script: |
              echo "GIT_TAG: $(GIT_TAG)"

          - download: "CI"
            name: "DownloadBuildArtifacts"
            displayName: Download Build Artifacts
            artifact: "app-v1.0"
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'sampleapp'
              Package: '$(Pipeline.Workspace)/CI/app-v1.0/iis-app.zip'